/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as ClientsVendorsRouteImport } from './routes/clients-vendors'
import { Route as IndexRouteImport } from './routes/index'

const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsVendorsRoute = ClientsVendorsRouteImport.update({
  id: '/clients-vendors',
  path: '/clients-vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients-vendors': typeof ClientsVendorsRoute
  '/organization': typeof OrganizationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients-vendors': typeof ClientsVendorsRoute
  '/organization': typeof OrganizationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients-vendors': typeof ClientsVendorsRoute
  '/organization': typeof OrganizationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clients-vendors' | '/organization'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clients-vendors' | '/organization'
  id: '__root__' | '/' | '/clients-vendors' | '/organization'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsVendorsRoute: typeof ClientsVendorsRoute
  OrganizationRoute: typeof OrganizationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients-vendors': {
      id: '/clients-vendors'
      path: '/clients-vendors'
      fullPath: '/clients-vendors'
      preLoaderRoute: typeof ClientsVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsVendorsRoute: ClientsVendorsRoute,
  OrganizationRoute: OrganizationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
